In [1]:
import numpy as np
import pandas as pd
import os
import datetime
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('user_info_withvalue.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 39 columns):
id                  3000 non-null int64
householder_name    3000 non-null object
per_num             3000 non-null int64
year                3000 non-null int64
ID_card             3000 non-null object
level               3000 non-null object
breed_year          0 non-null float64
equip_breed         0 non-null float64
land_year           0 non-null float64
land_size           0 non-null float64
channel             0 non-null float64
channel_num         0 non-null float64
sale_income         0 non-null float64
address             3000 non-null object
city_id             3000 non-null int64
city                3000 non-null object
county_id           3000 non-null int64
county              3000 non-null object
town_id             3000 non-null int64
town                3000 non-null object
village_id          3000 non-null int64
village_name        3000 non-null object
phone_num           0 non-null float64
helper              432 non-null object
helper_unit         439 non-null object
helper_number       427 non-null float64
plan_time           873 non-null object
help_industry       567 non-null object
industrial_scale    296 non-null object
tech_project        174 non-null object
income              3000 non-null int64
real_time           1 non-null object
out_poverty         3000 non-null object
input_user          17 non-null float64
input_time          17 non-null object
check_status        3000 non-null int64
status              3000 non-null int64
city_recorder       0 non-null float64
county_recorder     0 non-null float64
dtypes: float64(12), int64(10), object(17)
memory usage: 914.1+ KB

In [4]:
df_drop_na = df.drop(['householder_name', 'address', 'city', 'city_id','county', 'town', 'village_name', 
                            'phone_num','helper_number', 'input_user', 'input_time', 'city_recorder', 'county_recorder',
                            'helper','real_time','check_status'], axis=1)

#pandas series 迭代遍历
for index, row in df_drop_nacolumn.iterrows():
    print(row["income"]) 
###筛选异常数据

In [5]:
df_itter_income = df_drop_na[df_drop_na['income']< 100000]
df_itter_year = df_itter_income[df_itter_income['year']< datetime.datetime.now().year]

In [6]:
df_itter_year.info()
df_itter_year.describe()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2967 entries, 1 to 2999
Data columns (total 23 columns):
id                  2967 non-null int64
per_num             2967 non-null int64
year                2967 non-null int64
ID_card             2967 non-null object
level               2967 non-null object
breed_year          0 non-null float64
equip_breed         0 non-null float64
land_year           0 non-null float64
land_size           0 non-null float64
channel             0 non-null float64
channel_num         0 non-null float64
sale_income         0 non-null float64
county_id           2967 non-null int64
town_id             2967 non-null int64
village_id          2967 non-null int64
helper_unit         421 non-null object
plan_time           857 non-null object
help_industry       557 non-null object
industrial_scale    290 non-null object
tech_project        169 non-null object
income              2967 non-null int64
out_poverty         2967 non-null object
status              2967 non-null int64
dtypes: float64(7), int64(8), object(8)
memory usage: 556.3+ KB

,id,per_num,year,breed_year,equip_breed,land_year,land_size,channel,channel_num,sale_income,county_id,town_id,village_id,income,status
count,2.967000e+03,2967.000000,2967.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.967000e+03,2.967000e+03,2.967000e+03,2967.000000,2967.000000
mean,9.825034e+05,3.756657,2015.656892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.116862e+11,5.116863e+11,5.116863e+11,1089.729019,0.792383
std,5.321559e+05,1.708365,1.184685,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.286960e+08,9.287110e+08,9.287110e+08,1866.027135,0.610127
min,1.837200e+04,1.000000,2013.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.105220e+11,5.105221e+11,5.105221e+11,0.000000,-1.000000
25%,5.542025e+05,2.000000,2014.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.108240e+11,5.108241e+11,5.108241e+11,0.000000,1.000000
50%,9.979900e+05,4.000000,2016.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.117020e+11,5.117022e+11,5.117022e+11,0.000000,1.000000
75%,1.422330e+06,5.000000,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.119210e+11,5.119211e+11,5.119211e+11,2266.000000,1.000000
max,1.902650e+06,13.000000,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.134370e+11,5.134372e+11,5.134372e+11,29960.000000,1.000000

#更改 ID_CARD ，转换为年龄

In [7]:
ID_card = df_itter_year['ID_card']
ID_list = []
for item in ID_card:
    sl_item = datetime.datetime.now().year - int(item[6:10])
    ID_list.append(sl_item)
df_add_id = df_itter_year['ID_card'].replace(ID_list)

df.property_type = df.property_type.map({'F': '000', 'S': '001'})

In [8]:
income_region_crosstab = pd.crosstab(df_itter_year['income'], 
                                   df_itter_year['county_id'], 
                                   margins=True,
                                   normalize=False)
income_region_crosstab

county_id,510522000000,510524000000,510525000000,510726000000,510727000000,510802000000,510811000000,510812000000,510821000000,510822000000,...,513428000000,513429000000,513430000000,513431000000,513432000000,513434000000,513435000000,513436000000,513437000000,All
income,,,,,,,,,,,,,,,,,,,,,
0,155,36,1,27,14,4,0,5,0,2,...,12,69,25,28,17,4,0,6,8,1923
570,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
628,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
840,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
972,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1010,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1013,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1017,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1025,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1049,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1052,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1071,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,2
1074,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1076,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1083,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,2
1092,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1093,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1095,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1100,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1107,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
1114,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1126,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1140,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
1146,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1150,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1156,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
1160,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1166,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
1168,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1170,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6544,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6682,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6700,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6710,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6761,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7040,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7250,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7273,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7298,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7311,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7987,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8250,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8380,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8490,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8666,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9058,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9090,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9112,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9134,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9260,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9534,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
11560,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12251,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13120,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24140,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
28181,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
29960,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
All,199,77,23,27,14,4,5,5,68,6,...,17,69,25,32,17,36,23,31,20,2967